version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  postgresql:
    image: postgres
    container_name: postgresql
    environment:
      PG_DB_USERNAME: postgres
      PG_DB_PASSWORD: password
      PG_DB_DATABASE: game_item_management
      PG_DB_SCHEMA: game_server
    ports:
      - "5432:5432"

  nodejs_api:
    image: technical-test
    container_name: nodejs_api
    ports:
      - "7000:7500"
      - "5443:5443"
    environment:
      KAFKA_HOST: kafka:9092
      REDIS_HOST: redis
      PG_DB_DIALECT: postgresql
      PG_DB_USERNAME: postgres
      PG_DB_PASSWORD: password
      PG_DB_DATABASE: game_item_management
      PG_DB_SCHEMA: game_server
    depends_on:
      - kafka
      - redis
      - postgresql
